"""Added body_html and on_changed_body method for server-side markdown conversion

Revision ID: 066ebdbb4515
Revises: bfa48f4616ed
Create Date: 2025-09-05 18:05:22.737045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '066ebdbb4515'
down_revision = 'bfa48f4616ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
