"""added avatar_hash col to users

Revision ID: 721c0417056d
Revises: 0d336b83d267
Create Date: 2025-09-03 17:58:57.219148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721c0417056d'
down_revision = '0d336b83d267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
